[tool.black]
# check = true
exclude = '''
(
    PLACEHOLDER$
  # By parent directory
  # By specific pathname
  | bin/show_maybe_missed_source$
  # By file suffix
  # By more interesting patterns
  | bin/.*-run$
  | bin/all-.*$
  | bin/app-.*$
  | bin/dep-.*$
  | bin/env-.*$
  | bin/prj-.*$
  | bin/pve-.*$
  | bin/py-.*$
  | bin/show_maybe_missed_source$
  | bin/sig-.*$
  | bin/sync_on_macOS$
  | bin/tool-.*$
  # Project-specific
  | Jenkins/run$
  | bin/diff_.*$
  | bin/filter_.*$
  | cfg/DESIRED/.*$
  | home/\.ssh/.*$
  | home/bin/clone_.*$
  | home/bin/git_.*$
  | home/bin/grep_.*$
  | home/bin/secure$
  | home/Linux/\.config/.*$
  | home/macOS/\.config/.*$
  | home/macOS/\.inputrc$
  | home/macOS/\.zshrc$
)
'''
force-exclude = '''
(
    PLACEHOLDER$
  # By parent directory
  | \.anaconda/.*$
  | \.git/.*$
  | \.pytest_cache/.*$
  | __pycache__/.*$
  # By specific pathname
  | Dockerfile$
  | Jenkinsfile$
  | \.DS_Store$
  | \.bash_logout$
  | \.bash_profile$
  | \.bashrc$
  | \.coverage$
  | \.coveragerc$
  | \.gitignore$
  | \.grep-exclude-from$
  | \.mailmap$
  | \.profile$
  | \.xprofile$
  # By file suffix
  | \.avsc$
  | \.bash$
  | \.c$
  | \.cfg$
  | \.env$
  | \.log$
  | \.md$
  | \.java$
  | \.json$
  | \.nix$
  | \.out$
  | \.properties$
  | \.rst$
  | \.sh$
  | \.sig$
  | \.sql$
  | \.toml$
  | \.txt$
  | \.vim$
  | \.yaml$
  | \.yml$
  # By more interesting patterns
)
'''
include = ''
line-length = 79
target-version = ['py36']
# verbose = true

