[tool.black]
exclude = '''
(
    PLACEHOLDER$
  # By parent directory
  | \.anaconda/.*$
  | \.config/.*$
  | \.git/.*$
  | \.hg/.*$
  | \.pytest_cache/.*$
  | \.ssh/.*$
  | __pycache__/.*$
  | log/.*$
  | out/.*$
  | tmp/.*$
  # By specific pathname
  # By file suffix
  | \.avsc$
  | \.bash$
  | \.c$
  | \.cfg$
  | \.env$
  | \.java$
  | \.json$
  | \.log$
  | \.md$
  | \.nix$
  | \.out$
  | \.properties$
  | \.rst$
  | \.sh$
  | \.sig$
  | \.sql$
  | \.toml$
  | \.txt$
  | \.vim$
  | \.yaml$
  | \.yml$
  # By more interesting patterns
  | Dockerfile$
  | \.DS_Store$
  | \.bash_logout$
  | \.bash_profile$
  | \.bashrc$
  | \.coverage$
  | \.coveragerc$
  | \.gitignore$
  | \.grep-exclude-from$
  | \.inputrc$
  | \.mailmap$
  | \.profile$
  | \.xprofile$
  # Project-specific
  | bin/.*-run$
  | bin/all-.*$
  | bin/anaconda-.*$
  | bin/app-.*$
  | bin/env-.*$
  | bin/py-.*$
  | bin/show_.*$
  | bin/sig-.*$
  | bin/sync_.*$
  | bin/tool-.*$
  | home/bin/clone_.*$
  | home/bin/git_.*$
  | home/bin/grep_.*$
  | home/bin/secure$
)
'''

