#!/usr/bin/env bash
# Intended to be executed in a Bash shell.
# NO: set -o errexit -o nounset
set -o pipefail +o verbose +o xtrace
[[ "${BO_Trace:-UNDEFINED}" != UNDEFINED ]] && \
    1>&2 echo "DEBUG: Executing ${BASH_SOURCE}" && \
    [[ "${BO_Trace:-UNDEFINED}" == TRACE ]] && \
    1>&2 echo "DEBUG: Tracing ${BASH_SOURCE}" && \
    set -o verbose -o xtrace
# NO: trap ... EXIT
###############################################################################

main() {
    # Bootstrap BriteOnyx on a new development workstation
    # $1 = directory containing extracted archive file
    echo "Bootstrapping user '${USER}' on this workstation '$(hostname)'"
    local -r OS=$(uname)
    local -r DirTemp=$1

    maybe_backup_file "${HOME}/.bash_profile"
    maybe_backup_file "${HOME}/.spacemacs"

    distribute_archive "${DirTemp}"

    echo "Securing files"
    bash "${HOME}/bin/secure"

    echo "Updating and upgrading packages"
    # TODO: Manually install Homebrew until I can fully automate it
    # TODO: Homebrew checks for `sudo` access, so fully automate that too
#   homebrew-install
    homebrew-update
    homebrew-upgrade
    homebrew-populate

    prepare_git_access

    echo "You may configure the editors manually by invoking 'editors-configure'"

    return 0
}

main $@

###############################################################################
# NOTE: Uncomment these lines for debugging, placed where needed
# export PS4='$ ' ; set -vx
# Code to debug...
# set +vx

: << 'DisabledContent'
chsh -s /bin/bash
homebrew-install
editors-configure
vim ~/bin/lib/configure_paths.bash
ssh-keygen
clone_all
jump_workstation
bash -c "source activate.bash"
DisabledContent

